### ISSUE TITLE
GCC examples here

### ISSUE THREAD

**Issue by richelbilderbeek** [codecov/example-cpp#1]
Hi @stevepeak ,

I have described quite some examples using Codecov in my C++ Travis tutorial ( https://github.com/richelbilderbeek/travis_cpp_tutorial ). Here are some examples:

 * [![Build Status](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp98_gcov.svg?branch=master)](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp98_gcov) [travis_qmake_gcc_cpp98_gcov](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_gcov)
 * [![Build Status](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp11_boost_test_gcov.svg?branch=master)](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp11_boost_test_gcov) [travis_qmake_gcc_cpp11_boost_test_gcov](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_boost_test_gcov)
 * [![Build Status](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp11_gcov.svg?branch=master)](https://travis-ci.org/richelbilderbeek/travis_qmake_gcc_cpp11_gcov) [travis_qmake_gcc_cpp11_gcov](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_gcov)

If this work can be of any help to you, please let me know. Else, feel free to close this Issue.

**Comment by stevepeak** [comment]
Thanks @richelbilderbeek for these references. I think I'll create a readme on this project and direct people to checkout your integrations for the time being.
