### ISSUE TITLE
Nice example

### ISSUE THREAD

**Issue by agauniyal** [codecov/example-cpp#2]
?

**Comment by stevepeak** [comment]
Hey @agauniyal please see #1 for now. We will be publishing these examples to the repo itself soon. Thanks!

**Comment by agauniyal** [comment]
@stevepeak I saw it before opening this issue and all 3 examples show unknown coverage, probably because it's not working.

**Comment by stevepeak** [comment]
I think the badge links are just broken. Here is one of the repos on Codecov https://codecov.io/gh/richelbilderbeek/travis_qmake_gcc_cpp98_gcov/commit/6e0cc6bd5e7648ae224cb4ac2a77c9f1d4cb6331

Sorry about this mess... :( I've been working hard to tidy up.
